server:
  port: 1789
spring:
  application:
    name: enkeshu-nacos
  cloud:
    nacos:
      discovery:
        #namespace: public
        password: nacos
        server-addr: 127.0.0.1:8848
        username: nacos


